name: HDFHR Log Maintenance

# This workflow maintains database health by:
# 1. Archiving logs older than 3 months
# 2. Archiving oldest logs when the main table exceeds 700 records
# 3. Deleting oldest logs from archive when it exceeds 1000 records
# 4. Permanently deleting logs older than 1 year from the archive table

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  maintain-logs:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - name: Trigger log maintenance function
        run: |
          curl -X POST "${{ secrets.SUPABASE_URL }}/functions/v1/log-maintenance" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          -H "Content-Type: application/json"

      - name: Report maintenance status
        run: |
          echo "Log maintenance completed at $(date)"
          echo "Next scheduled run will be in 24 hours"
